apiVersion: v1
kind: Service
metadata:
  name: wsrestgestioncarrito
  namespace: dev
spec:
  ports:
    - name: http
      port: 18080
    - name: https
      port: 443
  type: LoadBalancer    
  selector:
    app: wsrestgestioncarrito