spring:
  application:
    name: wsRestGestionCarrito
server:
  port: 18080
eureka:
  client:
    serviceUrl:
      defaultZone: ${POC_EUREKA_URI}
  instance:
    preferIpAddress: true
    status-page-url-path: /v2/api-docs/
    health-check-url-path: /gestioncarrito/health
    virtual-host-name: SBBOGLAPPROJO7
    metadata-map:
      app-owner: Sophos Solutions
      description: Servicio que expone funcionalidades para la gestion del carrito